version: 2.1

jobs:
  build:
    docker:
      - image: node:alpine
    steps:
      - checkout
      - run: apk update && apk add curl curl-dev bash
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.06.3-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Building Docker Image
          command: "docker build -t pavanleton/shoppy -f ./server/node_server/Dockerfile.dev ./server/node_server"
      - run:
          name: Testing Node Server
          command: "docker run -e CI=true pavanleton/shoppy npm run test -- --coverage"
